export { default as Content } from './Content'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as MyCard } from './MyCard'
export { default as Plan } from './Plan'
export { default as Cards } from './Cards'
export { default as Plans } from './Plans'